### ISSUE TITLE
pnpmのロックファイルとnpmのロックファイルがどちらも含まれている

### ISSUE THREAD

**Issue by moko256** [misskey-dev/summaly#18]
pnpmのロックファイルであるpnpm-lock.yamlと、npmのロックファイルであるpackage-lock.jsonがどちらも含まれています。どちらかに統一していただきたいです。
また、README.mdではnpmを用いているものの、package.jsonにはpnpmの記載があり、一貫性がなくなっているように見えます。

経緯：
- #6 にてpnpm-lock.yamlが作成される
- 994f420b46c92b8a844855f016f8fb8830641a7c でpackage.jsonにpnpmが記載される

**Comment by tamaina** [comment]
pnpmでいいよなと思ったけどそういえばpnpmやめてくれって意見があったような気がする

**Comment by tamaina** [comment]
https://github.com/misskey-dev/browser-image-resizer/issues/8

npmに上げてくれという話だった
