### ISSUE TITLE
npm publish?

### ISSUE THREAD

**Issue by saschanaz** [misskey-dev/summaly#7]
NPMではいまも2.7.0が配信されていますが、3.0はNPMで配信しますか？

**Comment by tamaina** [comment]
@syuilo ?

**Comment by tamaina** [comment]
Pluginの仕様変更してv4にしちゃったけど

**Comment by tamaina** [comment]
（個人的にはGitでいいかなって思っており…）

**Comment by tamaina** [comment]
まあ確かに2.7.0がnpmに残ってるのは微妙ではあるな

**Comment by anatawa12** [comment]
misskeyのpackage.jsonをこまかく確認せずにnpmを当たった私も悪いのですが、更新されているレポジトリが移動しているのであれば syuilo/summarly archivedにするなど向こうが動いてないことをわかりやすくしていただけるとありがたいです

**Comment by tamaina** [comment]
やった
